<a href="https://colab.research.google.com/github/Warmillie/CLI-classes/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
vector = np.arange(1, 11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
matrix_3x3 = np.zeros((3, 3))
print(matrix_3x3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
matrix_5x5 = np.random.randint(1, 11, (5, 5))
print(matrix_5x5)

[[ 6  4  6  7  3]
 [ 5  6  7  1  4]
 [ 7  5  8  9  1]
 [ 8  2  9 10  8]
 [ 1  4  7  3  6]]


In [4]:
matrix_4x4 = np.random.rand(4, 4)
print(matrix_4x4)

[[0.48508448 0.05075115 0.04985496 0.88804262]
 [0.51391026 0.07779585 0.18881304 0.70827141]
 [0.9912616  0.86623397 0.33524998 0.50251519]
 [0.8469554  0.83811323 0.91864169 0.5812528 ]]


In [5]:
array_1 = np.random.randint(1, 11, 5)
array_2 = np.random.randint(1, 11, 5)
print("Масив 1:", array_1)
print("Масив 2:", array_2)
print("Додавання:", array_1 + array_2)
print("Віднімання:", array_1 - array_2)
print("Множення:", array_1 * array_2)

Масив 1: [10  4  5  1  8]
Масив 2: [4 6 6 6 7]
Додавання: [14 10 11  7 15]
Віднімання: [ 6 -2 -1 -5  1]
Множення: [40 24 30  6 56]


In [6]:
vector_1 = np.random.random(7)
vector_2 = np.random.random(7)
scalar_product = np.dot(vector_1, vector_2)
print("Вектор 1:", vector_1)
print("Вектор 2:", vector_2)
print("Скалярний добуток:", scalar_product)

Вектор 1: [0.56366797 0.82048999 0.07790545 0.13732209 0.18927657 0.92773677
 0.1291243 ]
Вектор 2: [0.45753025 0.795968   0.66721257 0.05835719 0.29862779 0.14928552
 0.18244933]
Скалярний добуток: 1.189551698214453


In [7]:
matrix_2x2 = np.random.randint(1, 11, (2, 2))
matrix_2x3 = np.random.randint(1, 11, (2, 3))
product_2x2_2x3 = np.dot(matrix_2x2, matrix_2x3)
print("Матриця 2x2:\n", matrix_2x2)
print("Матриця 2x3:\n", matrix_2x3)
print("Їхній добуток:\n", product_2x2_2x3)

Матриця 2x2:
 [[10 10]
 [ 3  3]]
Матриця 2x3:
 [[ 4 10  1]
 [10  2  6]]
Їхній добуток:
 [[140 120  70]
 [ 42  36  21]]


In [8]:
matrix_3x3_random = np.random.randint(1, 11, (3, 3))
inverse_matrix = np.linalg.inv(matrix_3x3_random)
print(matrix_3x3_random)
print("Її обернена матриця:")
print(inverse_matrix)

[[1 6 1]
 [6 2 9]
 [5 9 9]]
Її обернена матриця:
[[ 0.8630137   0.61643836 -0.71232877]
 [ 0.12328767 -0.05479452  0.04109589]
 [-0.60273973 -0.28767123  0.46575342]]


In [9]:
matrix_4x4_random = np.random.rand(4, 4)
transposed_matrix = np.transpose(matrix_4x4_random)
print(matrix_4x4_random)
print("Транспонована матриця:")
print(transposed_matrix)


[[0.51350973 0.4172769  0.40122964 0.66677692]
 [0.71217739 0.08485389 0.89164248 0.11781598]
 [0.37141138 0.07257115 0.75516104 0.45564389]
 [0.32339067 0.39048979 0.99774477 0.78788262]]
Транспонована матриця:
[[0.51350973 0.71217739 0.37141138 0.32339067]
 [0.4172769  0.08485389 0.07257115 0.39048979]
 [0.40122964 0.89164248 0.75516104 0.99774477]
 [0.66677692 0.11781598 0.45564389 0.78788262]]


In [10]:
matrix_3x4 = np.random.randint(1, 11, (3, 4))
vector_4 = np.random.randint(1, 11, 4)
product_3x4_vector = np.dot(matrix_3x4, vector_4)
print("Матриця 3x4:\n", matrix_3x4)
print("Вектор 4:", vector_4)
print("Їхній добуток:", product_3x4_vector)

Матриця 3x4:
 [[ 3  8  9  3]
 [ 1  1 10  1]
 [ 6 10  3  9]]
Вектор 4: [10  4  9  4]
Їхній добуток: [155 108 163]


In [11]:
matrix_2x3_random = np.random.rand(2, 3)
vector_3 = np.random.rand(3)
product_2x3_vector = np.dot(matrix_2x3_random, vector_3)
print("Матриця 2x3:\n", matrix_2x3_random)
print("Вектор 3:", vector_3)
print("Їхній добуток:", product_2x3_vector)

Матриця 2x3:
 [[0.45599214 0.47677746 0.44152745]
 [0.13165275 0.74762391 0.65516548]]
Вектор 3: [0.28066706 0.02494399 0.94558637]
Їхній добуток: [0.55737704 0.67511487]


In [12]:
matrix_a_2x2 = np.random.randint(1, 11, (2, 2))
matrix_b_2x2 = np.random.randint(1, 11, (2, 2))
elementwise_multiplication = matrix_a_2x2 * matrix_b_2x2
print("Матриця A:\n", matrix_a_2x2)
print("Матриця B:\n", matrix_b_2x2)
print("Поелементне множення:\n", elementwise_multiplication)

Матриця A:
 [[8 8]
 [3 7]]
Матриця B:
 [[8 9]
 [9 9]]
Поелементне множення:
 [[64 72]
 [27 63]]


In [13]:
matrix_a_2x2_product = np.dot(matrix_a_2x2, matrix_b_2x2)
print("\nДобуток двох матриць розміром 2x2:")
print(matrix_a_2x2_product)



Добуток двох матриць розміром 2x2:
[[136 144]
 [ 87  90]]


In [14]:
matrix_5x5_sum = np.random.randint(1, 101, (5, 5))
sum_elements = np.sum(matrix_5x5_sum)
print(matrix_5x5_sum)
print("Сума елементів матриці:", sum_elements)

[[10 75 10 26 79]
 [66 59 78 44 73]
 [53 15 51 43 41]
 [71 36 63  4 61]
 [34 58 66 24 49]]
Сума елементів матриці: 1189


In [15]:
matrix_a_4x4 = np.random.randint(1, 11, (4, 4))
matrix_b_4x4 = np.random.randint(1, 11, (4, 4))
difference = matrix_a_4x4 - matrix_b_4x4
print("Матриця A:\n", matrix_a_4x4)
print("Матриця B:\n", matrix_b_4x4)
print("Різниця:\n", difference)

Матриця A:
 [[ 8  4  8  3]
 [ 6  1  3 10]
 [ 2 10  4  5]
 [ 7  6  5  3]]
Матриця B:
 [[ 4  7  3  9]
 [ 8  6  6  9]
 [ 6  4  8  7]
 [ 9 10 10  2]]
Різниця:
 [[ 4 -3  5 -6]
 [-2 -5 -3  1]
 [-4  6 -4 -2]
 [-2 -4 -5  1]]


In [16]:
matrix_3x3_sums = np.random.rand(3, 3)
row_sums = np.sum(matrix_3x3_sums, axis=1).reshape(-1, 1)
print(matrix_3x3_sums)
print("Вектор-стовпчик сум кожного рядка:")
print(row_sums)

[[0.96428159 0.20950678 0.12646628]
 [0.70587356 0.51979711 0.74020355]
 [0.31394855 0.67329614 0.48306239]]
Вектор-стовпчик сум кожного рядка:
[[1.30025465]
 [1.96587422]
 [1.47030709]]


In [17]:
matrix_3x4_squares = np.random.randint(1, 11, (3, 4))
squared_matrix = np.square(matrix_3x4_squares)
print(matrix_3x4_squares)
print("Матриця з квадратами цих чисел:")
print(squared_matrix)

[[8 1 8 1]
 [7 2 3 3]
 [7 4 1 4]]
Матриця з квадратами цих чисел:
[[64  1 64  1]
 [49  4  9  9]
 [49 16  1 16]]


In [18]:
vector_4_sqrt = np.random.randint(1, 51, 4)
sqrt_vector = np.sqrt(vector_4_sqrt)
print(vector_4_sqrt)
print("Вектор з квадратними коренями цих чисел:")
print(sqrt_vector)

[44  3 22 29]
Вектор з квадратними коренями цих чисел:
[6.63324958 1.73205081 4.69041576 5.38516481]
